services:
    zikula_content_module.app_settings:
        class: Zikula\ContentModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula.cache_clearer"
